name: EthriaAddons
version: '${project.version}'
main: de.ethria.main.Main
api-version: '1.20'
authors: [DarkPlugins]
description: Just some Addons for Ethria
depend:
  - Vault
commands:
  eventchests:
  locatebiome:
